package challenges.leetcode;

import static com.google.common.truth.Truth.assertThat;

import java.util.List;

import challenges.AbstractCustomTestRunner;

/**
 * 389. Find the Difference
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * 
 * Example:
 * 		Input:
 * 			s = "abcd"
 * 			t = "abcde"
 * 
 * 		Output:
 * 			e
 * 
 * 		Explanation: 'e' is the letter that was added.
 * 
 * @author Hxkandwal
 *
 */
public class FindTheDifference extends AbstractCustomTestRunner {
	
	private static FindTheDifference _instance = new FindTheDifference();

	public char _findTheDifference(String s, String t) {
		if (s.length() == 0) return t.charAt(0);
        char sAsciiXor = s.charAt(0);
        for (int idx = 1; idx < s.length(); idx ++) sAsciiXor ^= s.charAt(idx);
        for (int idx = 0; idx < t.length(); idx ++) sAsciiXor ^= t.charAt(idx);
        return sAsciiXor;
    }

	public char _findTheDifferenceOther(String s, String t) {
		int [] map = new int [256];
		for (char ch : s.toCharArray ()) map [ch] ++;
		for (char ch : t.toCharArray ()) if (map [ch] -- == 0) return ch;
		return ' ';
	}
	
	// driver method
	public static void main(String[] args) {
		_instance.runTest("abcd", "abcde", 'e');
		_instance.runTest("abcfd", "abcdfe", 'e');
	}
	
	public void runTest(final String s, final String t, final char expectedOutput) {
		List<Object> answers = runAll(getClass(), new Object[] { s, t });
		
		for (Object answer : answers) 
			assertThat((Character) answer).isEqualTo(expectedOutput);
		
		System.out.println("ok!");
	}	

}
